baseURL = "https://fafa-space-wi7c.vercel.app/"
title = "fa"
theme = "PaperMod"

# 开启秒搜功能
[outputs]
home = ["HTML", "RSS", "JSON"]

# 导航菜单 (放在中间，确保它是顶级目录)
[menu]
  [[menu.main]]
    identifier = "home"
    name = "首页📃"
    url = "/"
    weight = 10
  [[menu.main]]
    identifier = "search"
    name = "搜索 🔍"
    url = "/search/"
    weight = 20
  [[menu.main]]
    identifier = "tags"
    name = "标签 🏷️"
    url = "/tags/"
    weight = 30
  [[menu.main]]
    identifier = "about"
    name = "关于我"
    url = "/about/"
    weight = 40

# 细节配置
[params]
env = "production"
defaultTheme = "light"
ShowToc = true
ShowShareButtons = false

  [params.homeInfoParams]
  Title = "Hi, is fa"
  Content = "把无法说的话都倒在这里🧊"