baseURL = "/"
title = "fa" # 左上角的标题名字
theme = "PaperMod"

# 这里是开启秒搜功能的关键
[outputs]
home = ["HTML", "RSS", "JSON"]

[params]
env = "production"
defaultTheme = "light" # 强制锁定浅色模式，让莫兰迪色完美呈现
ShowToc = true
ShowShareButtons = false

  # 首页的个人介绍文案，可以随便改
  [params.homeInfoParams]
  Title = "Hi, is fa"
  Content = "把无法说的话都倒在这里🧊"

  [menu]
  [[menu.main]]
    identifier = "about"
    name = "关于我"
    url = "/about/"
    weight = 40
  [[menu.main]]
    identifier = "home"
    name = "首页📃"
    url = "/"
    weight = 10
  [[menu.main]]
    identifier = "search"
    name = "搜索 🔍"
    url = "/search/"
    weight = 20
  [[menu.main]]
    identifier = "tags"
    name = "标签 🏷️"
    url = "/tags/"
    weight = 30